source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', ENV.fetch("RAILS_VERSION", "~>4.2.0")
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.13', '< 0.5'

if ENV["REQUIRE_VERSION"] != "NOTHING"
  gem "enforce_mysql_version", path: "../../", require: ENV["REQUIRE_VERSION"]
else
  gem "enforce_mysql_version", path: "../../"
end
