sudo: required
dist: trusty
language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
services:
  - docker

before_script:
  - docker-compose up -d
  - while ! nc -w 1 127.0.0.1 33055 2>/dev/null; do sleep 1; done
  - while ! nc -w 1 127.0.0.1 33056 2>/dev/null; do sleep 1; done
  - while ! nc -w 1 127.0.0.1 33057 2>/dev/null; do sleep 1; done

script:
  - bundle install
  - bundle install --gemfile spec/rails_app/Gemfile
  - bundle exec rspec
