sudo: required
dist: trusty
language: ruby
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
env:
  - RAILS_VERSION="~>4.0.0"
  - RAILS_VERSION="~>4.1.0"
  - RAILS_VERSION="~>4.2.0"
services:
  - docker

script:
  - bundle install
  - bundle exec rake
